### ISSUE TITLE
How can I know which demosaic method the camera use?

### ISSUE THREAD

**Issue by XinYu-Andy** [timothybrooks/unprocessing#1]
Hello, I have used python to open the raw file. And I can use rawpy class to obtain some parameters in the ISP process, like white balance, CCM. However, it didn't show which the demosaic method that the camera use. I want to implement the ISP process step by step by my own codes.

**Comment by timothybrooks** [comment]
I would recommend first looking through the raw image metadata to see if they record the Bayer pattern. If its not in the metadata but you know the camera/sensor that was used, you may be able to look up the Bayer pattern online from the sensor specification. If all else fails, you could try all permutations of RGGB, or look at the raw pixels to get an indication (green is typically brightest).
