### ISSUE TITLE
"noise calibration script" is unavailble.

### ISSUE THREAD

**Issue by chasecheng1218** [timothybrooks/unprocessing#3]
Hi Timothybrooks,
My camera contains no metadata of noise level.
The link of noise calibration script is unavailable, could you upload it?
Thank you
Chase

**Comment by timothybrooks** [comment]
Here is a corrected link to the script:
https://android.googlesource.com/platform/cts/+/806b430/apps/CameraITS/tests/dng_noise_model/dng_noise_model.py

This is just one approach for estimating shot and read noise from images. Many denoise dataset papers include other techniques, for example the Darmstadt Dataset paper has their own approach:
https://download.visinf.tu-darmstadt.de/papers/2017-cvpr-ploetz-benchmarking_denoising_algorithms-preprint.pdf
