### ISSUE TITLE
Usage of unprocess.py and process.py

### ISSUE THREAD

**Issue by jungdaechul-coderepo** [timothybrooks/unprocessing#4]
Hello!
First of all, thanks for your nice work.

I have encountered some problem while operating a unprocess.py and process.py

In my case, I tried to apply those code separately on my code.

In order to get raw data from some .png file I write a code as follow.

```Python
H_img=cv2.imread('test.png', cv2.IMREAD_UNCHANGED)
H_img=tf.convert_to_tensor(H_img, dtype=tf.float32)
unprocessImg=unprocess.unprocess(H_img)
processImg=process.process(unprocessImg[0], unprocessImg[1]['red_gain'],  unprocessImg[1]['blue_gain'],  unprocessImg[1]['cam2rgb'])
```

When process.py is operated I faced some error as below.
![image](https://user-images.githubusercontent.com/17921916/116216402-8c388200-a783-11eb-811e-b8451865d2a8.png)

I just want to get RGB->RAW->RGB data through your code.

How can I fix this problem?

Thanks in advance.

**Comment by AndreiBaraian** [comment]
@bigpicturejh How were you able to solve this? Stuck on the same thing. Actually I did manage to expand the dimensions, but after the pipeline, the image does not look the same. Any ideas?
